language: ruby

rvm: '2.2.3'

before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database peergear_test;' -U postgres

script:
  - export RAILS_ENV=test
  - bundle exec rake